load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("agent_bus")

python_library(
    name = "in_memory_agentbus",
    srcs = [
        "__init__.py",
        "in_memory_agentbus.py",
    ],
    # @lint-ignore BUCKLINT need base_module for OSS Python package structure
    base_module = "agentbus.test_util",
    typing = False,  # Disable type-checking for proto-generated types
    deps = [
        "//msl_infra/experimental/agentic/bus/proto:agent_bus_proto-python",
        "//msl_infra/experimental/agentic/bus/python/src/agentbus:agentbus_abc",
    ],
)
